name: Test CI

on:
    - pull_request
    - merge_group

jobs:
    Sleep:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Getting sleepy..."
                sleep 3m